### ISSUE TITLE
php_internal_file sets is_moodle_internal to false

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#10]
In classes/local/skel/php_internal_file.php, on line 49:
`$this->data['is_moodle_internal'] = false;`

Should 'is_moodle_internal' be set to true, as the name of the class suggests?

**Comment by mudrd8mz** [comment]
Oh yes. I forgot to put it back after developing the require of config.php.
well spotted!

**Comment by alexandru-elisei** [comment]
Do you think I should also check for the defined('MOODLE_INTERNAL') || die()) line in the PHPUnit tests? I think I should, it's part of the feature being implemented.

**Comment by mudrd8mz** [comment]
Yes, there should be a test for it so that we have full coverage.
