### ISSUE TITLE
Prepare for PHPUnit 9

### ISSUE THREAD

**Issue by ewallah** [mudrd8mz/moodle-tool_pluginskel#105]
assertContains() and assertNotContains() with string haystacks are deprecated and will not be supported in PHPUnit 9.

Moodle 3.10+ generates more than 60 refactor warnings to use assertStringContainsString()or assertStringContainsStringIgnoringCase().

This can be fixed from the command line for Moodle3.8+ versions:
```
cd admin/tool/pluginskel
find .  -name \*.php -exec sed -i "s/assertContains/assertStringContainsString/g" {} \;
find .  -name \*.php -exec sed -i "s/assertNotContains/assertStringNotContainsString/g" {} \;

```

**Comment by mudrd8mz** [comment]
Fixed in the said commit, to be released in the next version. Thanks.
