### ISSUE TITLE
Skeleton type for files

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#18]
This is regarding #15 and your comment on pull request #11.

If we decide that the skeleton type will check for the template variables I propose the following rule for deciding if we need a new class for a new class or we can use php_internal_file: 

If the template requires variables (other than those for the boilerplate), then create a skel type for that file where we can check for those variables. If the template doesn't require any variables (other than those for the boilerplate), like db/uninstall.php or settings.php, use the class php_internal_file.

**Comment by mudrd8mz** [comment]
Makes sense.

**Comment by alexandru-elisei** [comment]
After our discussion we've decided to not introduce another layer of complexity by having the skeleton class keep track of what recipe variables are needed to correctly generate the files from the templates.

The manager will keep track of these variables.
