### ISSUE TITLE
Logger object

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#2]
May I suggest that we permit the usage of a null logger when creating a new manager instance? 

If I don't want any logging done right now I need to create a logger with a stream handler that has the log level 'EMERGENCY'.

**Comment by mudrd8mz** [comment]
> If I don't want any logging

That's not common requirement, quite opposite. in either case, better way is probably to add a line like

```
$logger->pushHandler(new \Monolog\Handler\NullHandler());
```

**Comment by alexandru-elisei** [comment]
Ok, thank you, that works.
