### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#48]
I have been working on generating a theme plugin type by roughly following the guide from the [moodle docs](https://docs.moodle.org/dev/Creating_a_theme).

I've noticed that you can use the clean theme as the basis for a new theme. There's a [docs page](https://docs.moodle.org/dev/Clean_theme) about it.

Do you think I should add an option like clone_clean: true which will clone the clean theme (with variables from the recipe replaced, of course) and that will become the skeleton?

**Comment by mudrd8mz** [comment]
No. Let us focus on something very basic with the themes. There is an ongoing development in Moodle HQ to replace the clean as a default theme and it makes no sense to waste time on it.

**Comment by alexandru-elisei** [comment]
Seems reasonable, closing.
