### ISSUE TITLE
Atto plugins

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#54]
I've been working on Atto plugins and I'm trying to figure this out for hours.

There's a 'src' and a 'build' directory under yui. My guess is that the 'build' directory is built from the sources files under 'src', but how?

Or am I wrong and I should create the files under 'build' too?

**Comment by alexandru-elisei** [comment]
Found the answer, I need to use (Shifter)[https://docs.moodle.org/dev/YUI/Shifter] (or grunt).

I won't include the build directory, the developer will create it.

**Comment by mudrd8mz** [comment]
Correct.
