### ISSUE TITLE
Quotation marks  in skel/file/version.mustache

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#6]
According to [Moodle docs](https://docs.moodle.org/dev/version.php) there are no quotatin marks around the version property.

It works with the quotes, this is just a minor detail but I thought I mentioned it so the templates are according to the docs.

**Comment by mudrd8mz** [comment]
Version number is important field. We should validate it similarly to the regex that is used for $plugin->requires and use it without quotes.
