### ISSUE TITLE
Bugs mentioned in the Moodle dev meeting

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#77]
I've watched the Moodle dev meeting recording and you've mentioned that you are aware of several bugs in the plugin.

Can you post steps to reproduce them or any other relevant information that might be needed for fixing them?

**Comment by mudrd8mz** [comment]
I can't now recall the particular ones but it was more like tiny usability issues. I'll make sure to create proper issue report next time I hit them.
