### ISSUE TITLE
No install.xml

### ISSUE THREAD

**Issue by tmuras** [mudrd8mz/moodle-tool_pluginskel#82]
When generating activity module (and for other plugins possibly as well), install.xml is not created at all, so trying to install generated module results in:
```
mod_aaa

XML database file errors found

More information about this error
Debug info: File does not exist
Error code: ddlxmlfileerror 
```

**Comment by mudrd8mz** [comment]
Hmm. I am not sure this is something the generator should do. We have XMLDB for that and developers are supposed to use that to create the required DB scheme.

**Comment by tmuras** [comment]
I don't think you can use XMLDB for a module that is not installed... so there is no way for a developer to use it.

**Comment by mudrd8mz** [comment]
There is, although I admit it is a bit hacky as you have to visit /admin/tools/xmldb by typing it directly to the address bar (to not let Moodle trigger new mod installation). Anyway, you are right, we should generate a simple bare minimal table for mods to make things easier.

**Comment by kritisingh1** [comment]
@mudrd8mz since https://github.com/mudrd8mz/moodle-tool_pluginskel/commit/076bf767548d7fe0a1d37af5a53f23e7452bf7d7 is already there, is there anything else that needs to be done to mark this issue solved?

**Comment by mudrd8mz** [comment]
No, it should be all. Thanks.
