### ISSUE TITLE
Upgrade.php not working when building a mod

### ISSUE THREAD

**Issue by luukverhoeven** [mudrd8mz/moodle-tool_pluginskel#90]
Thanks for building this plugin in the first place. Its very handy way to start building a plugin. I found a small issue, the component name used in `upgrade.php` is incorrect when you building a mod. 

This should not contain mod_name but only the name. I think only `mod` should be without the plugin type.

![image](https://user-images.githubusercontent.com/995760/46634329-cb187500-cb50-11e8-8f09-c5bb4bd974f9.png)

--

![image](https://user-images.githubusercontent.com/995760/46634671-e33cc400-cb51-11e8-9c91-b5b0e9483945.png)

![image](https://user-images.githubusercontent.com/995760/46634405-192d7880-cb51-11e8-8fd5-f9a6c6a14477.png)

**Comment by luukverhoeven** [comment]
hmm maybe I did something wrong, on multiple places there is mod_ where it shouldn't be.

**Comment by mudrd8mz** [comment]
Thanks Luuk. You are right. I can confirm that in case of activity modules, the "mod_" should not be here. This is a known legacy from early versions of Moodle. Activity modules were the first plugins for it and there was no convention of using the type prefix by that time. So in many places, activity modules are not supposed to provide the "mod_" prefix, and many places where they are.

Meanwhile, please fix your plugin's code manually. Than you for letting me know about this.
