### ISSUE TITLE
No web interface

### ISSUE THREAD

**Issue by carpiediem** [mudrd8mz/moodle-tool_pluginskel#96]
The Moodle docs [include](https://docs.moodle.org/37/en/Plugin_skeleton_generator) this feature as far back as version 3.1, but I can't seem to find it anywhere in the web interface. What am I missing?

Edit: I don't see it in `MOODLE_ROOT_DIRECTORY/admin/tool/` either, for that matter...

**Comment by mudrd8mz** [comment]
Because it is a contributed plugin that has to be installed additionally from https://moodle.org/plugins/tool_pluginskel

**Comment by carpiediem** [comment]
Aha! Thanks. Perhaps you could add that link to the README file or documentation page? [This](https://docs.moodle.org/37/en/Plugin_skeleton_generator) is the only page that showed up in my search results.

**Comment by mudrd8mz** [comment]
Pull requests are welcome :-)
